### ISSUE TITLE
bootable image

### ISSUE THREAD

**Issue by ghost** [sergev/4.4BSD-Lite2#4]

**Comment by sergev** [comment]
Thank you, Nicolas!

The purpose of this repo is to preserve the sources of 4.4BSD as a historical artifact. So that people can study it and learn from it. The only file I added is README.md. Here I listed all the documents present in the distribution. 

For more information about 4.4BSD I would recommend this book: https://www.amazon.com/gp/product/0201549794/

4.4BSD is not a complete Unix system. You cannot just compile it and build a complete image to run. A few key components are missing. Over the years, several full scale Unix variants were developed based on 4.4BSD: FreeBSD, NetBSD, OpenBSD and others. The most genuine one is LiteBSD. You can find it here: https://github.com/sergev/LiteBSD
